<html>
    <head>
        <title>Edm Default Front End</title>
        <link rel="stylesheet" href="module-templates/edm-default-ui/css/desktop-screen.css" />
    </head>
    <body>
        <div id="wrapper">
            <header class="bg-3 c-A clearfix">
                <div class="container_16">
                    <h1 class="grid_16">Edm Default From End</h1>
                </div>
            </header>
            <!-- /header -->

            <nav class="bg-5 c-C clearfix">
                <div class="container_16">
                    <div class="grid_16">
                        <ul class="main menu horiz-menu-left">
                            <li><a href=""><span>Main</span></a>
                                <ul class="dNone">
                                    <li><a href=""><span>Link</span></a></li>
                                    <li><a href=""><span>Link</span></a></li>
                                    <li><a href=""><span>Link</span></a></li>
                                    <li><a href=""><span>Link</span></a></li>
                                </ul>
                            </li>
                            <li><a href=""><span>Blog</span></a></li>
                            <li><a href=""><span>Other</span></a></li>
                            <li><a href=""><span>Contact</span></a></li>
                            <li><a href=""><span>Site Map</span></a></li>
                        </ul>
                    </div>
                </div>
            </nav>

            <section class="after-header bg-8 c-F clearfix">
                <div class="container_16">
                    <div class="grid_16">
                        <p>After Header</p>
                    </div>
                </div>
            </section>
            <!-- /section.after-header -->

            <section class="main bg-F c-8 clearfix">
                <div class="container_16">
                    <div id="main" class="grid_12">
                        <?= $this->layout()->content; ?>
                        <div class="module articles">
                            <article>
                                <header>
                                    <h3><span>Article Title</span></h3>
                                </header>
                                <section>
                                    <p>This is the Article Body</p>
                                </section>
                                <footer>
                                    <p>This is the footer</p>
                                </footer>
                            </article>
                            <article>
                                <header>
                                    <h3><span>Article Title</span></h3>
                                </header>
                                <section>
                                    <p>This is the Article Body</p>
                                </section>
                                <footer>
                                    <p>This is the footer</p>
                                </footer>
                            </article>
                            <article>
                                <header>
                                    <h3><span>Article Title</span></h3>
                                </header>
                                <section>
                                    <p>This is the Article Body</p>
                                </section>
                                <footer>
                                    <p>This is the footer</p>
                                </footer>
                            </article>
                            <article>
                                <header>
                                    <h3><span>Article Title</span></h3>
                                </header>
                                <section>
                                    <p>This is the Article Body</p>
                                </section>
                                <footer>
                                    <p>This is the footer</p>
                                </footer>
                            </article>
                            <article>
                                <header>
                                    <h3><span>Article Title</span></h3>
                                </header>
                                <section>
                                    <p>This is the Article Body</p>
                                </section>
                                <footer>
                                    <p>This is the footer</p>
                                </footer>
                            </article>
                        </div>
                    </div>
                    <div id="right" class="bg-c grid_4">
                        <div class="module">
                            <header><h4>Blog Categories</h4></header>
                            <nav>
                                <ul class="menu">
                                    <li><a href=""><span>Link</span></a></li>
                                    <li><a href=""><span>Link</span></a></li>
                                    <li><a href=""><span>Link</span></a></li>
                                    <li><a href=""><span>Link</span></a>
                                        <ul>
                                            <li><a href=""><span>Link</span></a></li>
                                            <li><a href=""><span>Link</span></a></li>
                                            <li><a href=""><span>Link</span></a></li>
                                            <li><a href=""><span>Link</span></a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </nav>
                        </div> <!-- /blog categoriees -->

                        <div class="module">
                            <header>
                                <h4>Search</h4>
                            </header>
                            <div>
                                <form action="">
                                    <input type="text" />
                                    <input type="submit" value=">>" />
                                </form>
                            </div>
                        </div> <!-- /search -->
                        <br class="cb" />
                    </div>
                </div>
            </section>
            <!-- /section.main -->

            <section class="before-footer bg-8 c-F clearfix">
                <div class="container_16">
                    <div class="grid_16">
                        <p>Before foooter</p>
                    </div>
                </div>
            </section> <!-- /.before-footer -->

            <footer class="bg-3 c-A">
                <div class="container_16">
                    <div class="grid_16">
                        <ul class="menu horiz-menu-left">
                            <li><a href=""><span>Link</span></a></li>
                            <li><a href=""><span>Link</span></a></li>
                            <li><a href=""><span>Link</span></a></li>
                            <li><a href=""><span>Link</span></a></li>
                        </ul>
                    </div>
                    <div class="grid_4">
                        <p>&copy;2013</p>
                    </div>
                </div> <!-- /.container_16 -->
                <br class="cb" />
            </footer>

        </div> <!-- /#wrapper -->

    </body>
</html>
