<html>
    <head>
        <title>Edm Default Front End</title>
    </head>
    <body>
        <div id="wrapper">
            <header>
                <div>
                    <h1>Edm Default From End</h1>
                </div>
            </header>
            <section class="after-header">
                <div>
                    
                </div>
            </section>
            <section class="main">
                <div>
                    <?= $this->layout()->content; ?>
                </div>
            </section>
            <section class="before-footer">
                <div>
                    
                </div>
            </section>
            <footer>
                <div>
                    
                </div>
            </footer>
        </div>
    </body>
</html>
