<?php
$form = $this->form;
echo <<<HTML
    <form id="term-form" method="{$form->getAttribute('method')}" 
        action="{$form->getAttribute('action')}">
        <fieldset>
            <legend>Term Form</legend>
            {$this->edmFormElement($form->get('name'))}
            {$this->edmFormElement($form->get('alias'))}
            {$this->edmFormElement($form->get('term_group_alias'))}
        </fieldset>
        <fieldset class="controls">
            <div class="form-item">
            {$this->formElement($form->get('submit'))}
            {$this->formElement($form->get('reset'))}
            </div>
        </fieldset>
    </form>
HTML;
            