<?php

$form = $this->form;
$viewModule = $form->get('view-module-fieldset');
$mixedTermRel = $form->get('mixed-term-rel-fieldset');
$userParams = $form->get('user-params-fieldset');
$submitAndReset = $form->get('submit-and-reset');
//\Zend\Debug\Debug::dump($userParams->get('userParams')); exit();
echo <<<HTML
    <form id="{$form->getName()}" 
        method="{$form->getAttribute('method')}" 
        action="{$form->getAttribute('action')}">
        <fieldset>
            <legend>viewModule</legend>
            {$this->edmFormElement($viewModule->get('title'))}
            {$this->edmFormElement($viewModule->get('alias'))}<br class="cb" />
            {$this->edmFormElement($viewModule->get('type'))}
            {$this->edmFormElement($viewModule->get('helperName'))}
            {$this->edmFormElement($viewModule->get('helperType'))}<br class="cb" />
            {$this->edmFormElement($viewModule->get('partialScript'))}<br class="cb" />
            {$this->edmFormElement($viewModule->get('content'))}
        </fieldset>
        <fieldset>
            <legend>Category</legend>
            {$this->edmFormElement($mixedTermRel->get('term_taxonomy_id'))}
            {$this->edmFormElement($mixedTermRel->get('status'))}
            {$this->edmFormElement($mixedTermRel->get('accessGroup'))}
        </fieldset>
        <fieldset class="allowed-on-pages">
            <legend>Allowed on Pages</legend>
            {$this->edmFormCollection($viewModule->get('allowedOnPages'))}
        </fieldset>
        <fieldset class="user-params">
            <legend>User Params</legend>
            {$this->edmFormCollection($userParams->get('userParams'))}
        </fieldset>
        <fieldset class="controls">
            <div class="form-item">
            {$this->formElement($submitAndReset->get('submit'))}
            {$this->formElement($submitAndReset->get('reset'))}
            </div>
        </fieldset>
    </form>
HTML;

