<?php

// Form
$form = $this->form;

// User Fieldset
$user = $form->get('user');

// Contact Fieldset
$contact = $form->get('contact');

// Submit and Reset Fieldset
$submitAndReset = $form->get('submit-and-reset');

// Output html
echo <<<HTML
    <form id="{$form->getName()}" 
        method="{$form->getAttribute('method')}" 
        action="{$form->getAttribute('action')}">
        <fieldset>
            <legend>Contact Info</legend>
            {$this->edmFormElement($contact->get('name'))}
            {$this->edmFormElement($contact->get('firstName'))}
            {$this->edmFormElement($contact->get('middleName'))}
            {$this->edmFormElement($contact->get('lastName'))}
        </fieldset>
        <fieldset>
            <legend>User</legend>
            {$this->edmFormElement($user->get('screenName'))}<br class="cb" />
            {$this->edmFormElement($user->get('status'))}
            {$this->edmFormElement($user->get('role'))}
            {$this->edmFormElement($user->get('accessGroup'))}
        </fieldset>
        <fieldset class="controls">
            <div class="form-item">
            {$this->formElement($submitAndReset->get('submit'))}
            {$this->formElement($submitAndReset->get('reset'))}
            </div>
        </fieldset>
    </form>
HTML;

