<?php

$form           = $this->form;
$page           = $form->get('page-fieldset');
$menuPageRel    = $form->get('menu-page-rel-fieldset');
$mixedTermRel   = $form->get('mixed-term-rel-fieldset');
$mvcParams      = $form->get('mvc-params-fieldset');
$otherParams    = $form->get('other-params-fieldset');
$submitAndReset = $form->get('submit-and-reset');

echo <<<HTML
    <form id="{$form->getName()}" 
        method="{$form->getAttribute('method')}" 
        action="{$form->getAttribute('action')}">
        <fieldset>
            <legend>Link Info</legend>
            {$this->edmFormElement($page->get('label'))}
            {$this->edmFormElement($page->get('alias'))}<br class="cb" />
        </fieldset>
        <fieldset>
            <legend>Page Type</legend>
            {$this->edmFormElement($page->get('type'))}<br class="cb" />
            <div class="form-item clear-both">
                <label>Uri Page</label><br />
                {$this->edmFormElement($page->get('uri'))}
                {$this->edmFormElement($page->get('acl_resource'))}
                {$this->edmFormElement($page->get('acl_privilege'))}
            </div>
            <div class="form-item clear-both">
                <label>Mvc Page</label><br />
                {$this->edmFormElement($page->get('mvc_action'))}
                {$this->edmFormElement($page->get('mvc_controller'))}
                {$this->edmFormElement($page->get('mvc_module'))}
                {$this->edmFormElement($page->get('mvc_route'))}
                {$this->edmFormElement($page->get('mvc_resetParamsOnRender'))}
                <br class="clear-both" />
                <fieldset>
                    <legend>Mvc Params</legend>
                    {$this->edmFormCollection($mvcParams->get('userParams'))}
                </fieldset>
            </div>
        </fieldset>
        <fieldset>
            <legend>Associations</legend>
            {$this->edmFormElement($mixedTermRel->get('term_taxonomy_id'))}
            {$this->edmFormElement($page->get('parent_id'))}
            {$this->edmFormElement($form->get('menu-page-rel-fieldset')->get('menu_id'))}   
        </fieldset>
        <fieldset>
            <legend>Permissions</legend>
            {$this->edmFormElement($mixedTermRel->get('status'))}<br class="clear-both" />
            {$this->edmFormElement($page->get('description'))}<br class="clear-both" />
            {$this->edmFormElement($page->get('visible'))}
            {$this->edmFormElement($mixedTermRel->get('accessGroup'))}
        </fieldset>
        <fieldset class="other-params">
            <legend>Other Params (html params, and other user defined params etc.)</legend>
            {$this->edmFormCollection($otherParams->get('userParams'))}
            <div class="controls">
                <div class="form-item float-right">
                    <button class="less btn big-btn">-</button>
                    <button class="more btn big-btn">+</button>
                </div>
            </div>
        </fieldset>
        <fieldset class="controls">
            <div class="form-item">
            {$this->formElement($mixedTermRel->get('objectType'))}
            {$this->formElement($submitAndReset->get('submit'))}
            {$this->formElement($submitAndReset->get('reset'))}
            </div>
        </fieldset>
    </form>
HTML;
