<?php

$form = $this->form;
$post = $form->get('post-fieldset');
$postTermRel = $form->get('post-term-rel-fieldset');
$userParams = $form->get('user-params-fieldset');
//\Zend\Debug\Debug::dump($this->formCollection($userParams->get('userParams')));
$submitAndReset = $form->get('submit-and-reset');
echo <<<HTML
    <form id="{$form->getName()}" 
        method="{$form->getAttribute('method')}" 
        action="{$form->getAttribute('action')}">
        <fieldset>
            <legend>Post</legend>
            {$this->edmFormElement($post->get('title'))}
            {$this->edmFormElement($post->get('alias'))}<br class="cb" />
            {$this->edmFormElement($post->get('content'))}<br class="cb" />
            {$this->edmFormElement($post->get('excerpt'))}<br class="cb" />
            {$this->edmFormElement($post->get('commenting'))}
            {$this->edmFormElement($post->get('status'))}
            {$this->edmFormElement($post->get('accessGroup'))}
            {$this->edmFormElement($post->get('type'))}
        </fieldset>
        <fieldset>
            <legend>Category</legend>
            {$this->edmFormElement($postTermRel->get('term_taxonomy_id'))}
        </fieldset>
        <fieldset class="user-params">
            <legend>User Params</legend>
            {$this->edmFormCollection($userParams->get('userParams'))}
        </fieldset>
        <fieldset class="controls">
            <div class="form-item">
            {$this->formElement($submitAndReset->get('submit'))}
            {$this->formElement($submitAndReset->get('reset'))}
            </div>
        </fieldset>
    </form>
HTML;

