<?php

// Form
$form = $this->form;


// Submit and Reset Fieldset
$submitAndReset = $form->get('submit-and-reset');

// Output html
echo <<<HTML
    <form id="{$form->getName()}" 
        method="{$form->getAttribute('method')}" 
        action="{$form->getAttribute('action')}">
        <fieldset class="controls">
            <legend>Login form</legend>
            {$this->edmFormElement($form->get('screenName'))}<br class="cb" />
            {$this->edmFormElement($form->get('password'))}<br class="cb" />
            <div class="form-item">
            {$this->formElement($submitAndReset->get('submit'))}
            {$this->formElement($submitAndReset->get('reset'))}
            </div>
        </fieldset>
    </form>
HTML;

