<?php
$menu = $this->form->get('secondary-fieldset');
echo <<<HTML
        <fieldset>
            <legend>Menu</legend>
            {$this->edmFormElement($menu->get('minDepth'))}
            {$this->edmFormElement($menu->get('maxDepth'))}
            {$this->edmFormElement($menu->get('onlyActiveBranch'))}
            {$this->edmFormElement($menu->get('renderParents'))}
            {$this->edmFormElement($menu->get('isMainMenu'))}
            {$this->edmFormElement($menu->get('useModuleHelper'))}
            {$this->edmFormElement($menu->get('ulClass'))}
            {$this->edmFormElement($menu->get('menuPartialScript'))}
            {$this->edmFormElement($menu->get('menuHelper'))}
        </fieldset>
HTML;
            