<!DOCTYPE html>
<html>
    <head>
        <title>Edm Cms - Ajax Interface</title>
        <meta charset="utf-8">
        <link rel="stylesheet"
              href="http://fedls/jquery-ui-1.9.2.custom/css/sunny/jquery-ui-1.9.2.custom.min.css"
              media="all" />
        <link rel="stylesheet/less" href="/module-templates/edm-ko-ui/less/main.less" media="all" />
        <link rel="stylesheet" href="http://fedls/960-fluid.css" media="all" />
        <script data-main="/module-templates/edm-ko-ui/src/edm/main" 
                src="http://fedls/require.js"></script>
    </head>
    <body>
        <div id="wrapper">

            <header>
                <h1 class="fl">Edm Cms</h1>
                <div class="user-controls fl">
                    <a href="#!/user/logout">Log out</a>
                </div>
            </header>

            <nav>
                <!-- ko template: {name: 'ul-menu-tmpl'} --><!-- /ko -->
            </nav>

            <section>
                <div id="left" class="bg-c fl">
                    <div class="handle controls">
                        <a href="#"><span>&gt;&gt;</span></a>
                    </div>
                    <div id="content-sub-menu"
                         data-bind="template: {name: 'left-col-menu-module-tmpl'}">
                    </div>
                    <div id="system-sub-menu" 
                         data-bind="template: {name: 'left-col-menu-module-tmpl'}">
                    </div>
                    <div id="view-module-sub-menu" 
                         data-bind="template: {name: 'left-col-menu-module-tmpl'}">
                    </div>
                    <br class="cb" />
                </div><!--/#left-->

                <div id="main" class="fl">
                </div> <!-- /#main -->
            </section> <!-- /main content section -->
            
            <footer>
                &copy;2012 and beyond <a href="http://elycruz.com">ElyCruz</a>
            </footer>
            
        </div> <!-- /#wrapper -->

        <!-- SCRIPTS 
        \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\-->

    </body>
</html>
