     <!--
      See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
      -->
      <?php if ($this->pageCount): ?>
      <div class="form-item pagination-control">
      <!-- Previous page link -->
      <?php if (isset($this->previous)): ?>
        <a href="<?= $this->url(array('page' => $this->previous)); ?>">
          <span>&lt; Previous</span>
        </a>
      <?php else: ?>
        <span class="disabled">&lt; Previous</span>
      <?php endif; ?>
      <!-- Numbered page links -->
      <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
          <a href="<?= $this->url(array('page' => $page)); ?>">
				<span><?php echo $page; ?></span>
          </a>
        <?php else: ?>
                            <span class="current"><?php echo $page; ?></span>
        <?php endif; ?>
      <?php endforeach; ?>
      <!-- Next page link -->
      <?php if (isset($this->next)): ?>
        <a href="<?= $this->url(array('page' => $this->next)); ?>">
          <span>Next &gt;</span>
        </a>
      <?php else: ?>
        <span class="disabled">Next &gt;</span>
      <?php endif; ?>
      </div>
        <div class="form-item font-georgia italic">Showing
            <?= $this->firstItemNumber .'-'.
          $this->lastItemNumber .' of '. $this->totalItemCount; ?>
      </div>
      <?php endif; ?>