<?php
$form = $this->form;

$term = $form->get('term');
$termTax = $form->get('term-taxonomy');
$submitAndReset = $form->get('submit-and-reset');

echo <<<HTML
    <form id="{$form->getName()}" 
        method="{$form->getAttribute('method')}" 
        action="{$form->getAttribute('action')}">
        <fieldset>
            <legend>Term</legend>
            {$this->edmFormElement($term->get('name'))}
            {$this->edmFormElement($term->get('alias'))}
            {$this->edmFormElement($term->get('term_group_alias'))}
        </fieldset>
        <fieldset>
            <legend>Taxonomy</legend>
            {$this->edmFormElement($termTax->get('taxonomy'))}
            {$this->edmFormElement($termTax->get('parent_id'))}
            {$this->edmFormElement($termTax->get('description'))}
            {$this->edmFormElement($termTax->get('accessGroup'))}
        </fieldset>
        <fieldset class="controls">
            <div class="form-item">
            {$this->formElement($submitAndReset->get('submit'))}
            {$this->formElement($submitAndReset->get('reset'))}
            </div>
        </fieldset>
    </form>
HTML;

